
### ----------------------------------
### User API
### ----------------------------------

###
// Get all users
GET http://localhost:6600/api/v1/users
Content-Type: application/json


###
// Get a user
GET http://localhost:6600/api/v1/users/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJsb2dpbkB1c2VyLmNvbSIsImlhdCI6MTU5MzA2ODc1Nn0.npJubyKAJ9-cQjtD5HqDZOHlmKPgf8PkZJycj_a_lbk
Content-Type: application/json


###
// Create a user
POST http://localhost:6600/api/v1/users
Content-Type: application/json

{
  "user": {
    "email": "login@user.com",
    "password": "login-pass"
  }
}


###
// Delete a user
DELETE http://localhost:6600/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImVtYWlsIjoibG9naW5AdXNlci5jb20iLCJpYXQiOjE1OTMwMTk1MTV9.V5cZ6nh-fgyI2LK6hEZmF7WHnDthAsAnpAk2Jew9gMM
Content-Type: application/json


###
// Update a user
PUT http://localhost:6600/api/v1/users/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJsb2dpbkB1c2VyLmNvbSIsImlhdCI6MTU5MzA3MzAwN30.CK8VUyftvfrfmiQ7LQ95A2WrqYgxFngxlzMEhM0m6IA
Content-Type: application/json

{
  "user": {
    "email": "login@user.com",
    "password": "login-pass"
  }
}


###
// Login a user
POST http://localhost:6600/api/v1/login
Content-Type: application/json

{
  "user": {
    "email": "login@user.com",
    "password": "login-pass"
  }
}