
### ----------------------------------
### User API
### ----------------------------------

###
// Get a user
GET http://localhost:6600/api/v1/users
Content-Type: application/json


###
// Create a user
POST http://localhost:6600/api/v1/users
Content-Type: application/json

{
  "user": {
    "email": "new@user.com",
    "password": "new-pass"
  }
}


###
// Create a user
DELETE http://localhost:6600/api/v1/users/3
Content-Type: application/json

