version: '3'

services:
  db-mysql:
    container_name: db-mysql
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3308:3306

  node-sequelize:
    container_name: node-sequelize
    image: node:10.21.0-stretch-slim
    restart: always
    command: bash -c "
      cd /home/node/app
      && npm install
      && npm run test
      && npm run dev
      "
    volumes:
      - .:/home/node/app
    ports:
      - 6600:6600
    depends_on:
      - db-mysql
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
