version: '3'

services:
  db-mysql:
    container_name: db-mysql
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3308:3306

  node-sequelize:
    container_name: node-sequelize
    image: node:10.21.0-stretch-slim
    restart: always
    command: bash -c "
      cd /home/node/app
      && npm install
      && npm run test
      && npm start
      "
    volumes:
      - .:/home/node/app
    ports:
      - 6600:6600
    depends_on:
      - db-mysql
