
### ----------------------------------
### Controller API
### ----------------------------------


###
// Get a quiz
GET http://localhost:6600/api/v1/quizzes/5f1385d60c76680e24a185a6
Content-Type: application/json


###
// Create a quiz for a user id
POST http://localhost:6600/api/v1/quizzes/5f148144dbbc292c38a110f2
Content-Type: application/json

###

