
### ----------------------------------
### Controller API
### ----------------------------------


###
// Get a quiz
GET http://localhost:6600/api/v1/quizzes/5f14a0a5606d694572f4882a
Content-Type: application/json


###
// Create a quiz for a user id
POST http://localhost:6600/api/v1/quizzes/5f1481e3dbbc292c38a110f3
Content-Type: application/json

###

